// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhq2wNv-Et68HX_sIJdzxeuzAcE5oHqc',
    appId: '1:160391868467:web:acf76a8773a933859e3346',
    messagingSenderId: '160391868467',
    projectId: 'tatva-academy',
    authDomain: 'tatva-academy.firebaseapp.com',
    storageBucket: 'tatva-academy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRcfxUoa-SIRoahIUlXtEbLX0pzNBKD8',
    appId: '1:160391868467:android:8bfcb01f04577aff9e3346',
    messagingSenderId: '160391868467',
    projectId: 'tatva-academy',
    storageBucket: 'tatva-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZFAPTpg0tUQHgwfB_-EerPi7Y9BpaFxk',
    appId: '1:160391868467:ios:a80d8afdf8d885269e3346',
    messagingSenderId: '160391868467',
    projectId: 'tatva-academy',
    storageBucket: 'tatva-academy.firebasestorage.app',
    iosBundleId: 'com.example.tatva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZFAPTpg0tUQHgwfB_-EerPi7Y9BpaFxk',
    appId: '1:160391868467:ios:a80d8afdf8d885269e3346',
    messagingSenderId: '160391868467',
    projectId: 'tatva-academy',
    storageBucket: 'tatva-academy.firebasestorage.app',
    iosBundleId: 'com.example.tatva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFhq2wNv-Et68HX_sIJdzxeuzAcE5oHqc',
    appId: '1:160391868467:web:c10f075f7e9dfe789e3346',
    messagingSenderId: '160391868467',
    projectId: 'tatva-academy',
    authDomain: 'tatva-academy.firebaseapp.com',
    storageBucket: 'tatva-academy.firebasestorage.app',
  );
}
