// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-CWy_oSvxS6ZpiB-NKxokaKwnV9cYjc',
    appId: '1:859841471446:web:53ea03aa5a1d7d74a63a77',
    messagingSenderId: '859841471446',
    projectId: 'tatva-school-app',
    authDomain: 'tatva-school-app.firebaseapp.com',
    storageBucket: 'tatva-school-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-yTLF3sb-et_GjlAS6XCy7OVLvAs8YRY',
    appId: '1:859841471446:android:6feb3a04db6c74b9a63a77',
    messagingSenderId: '859841471446',
    projectId: 'tatva-school-app',
    storageBucket: 'tatva-school-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_hoHgEUyu0e3XDOze5jFKKpajW-MCE_o',
    appId: '1:859841471446:ios:83e51016c097dfbba63a77',
    messagingSenderId: '859841471446',
    projectId: 'tatva-school-app',
    storageBucket: 'tatva-school-app.firebasestorage.app',
    iosBundleId: 'com.tatva.school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_hoHgEUyu0e3XDOze5jFKKpajW-MCE_o',
    appId: '1:859841471446:ios:83e51016c097dfbba63a77',
    messagingSenderId: '859841471446',
    projectId: 'tatva-school-app',
    storageBucket: 'tatva-school-app.firebasestorage.app',
    iosBundleId: 'com.tatva.school',
  );
}
